frame: "gps_origin"

land_at_the_end: false

minimum_height: 2.0 # [m]

flocking:
  # Experiment parameters
  auto_start: false
  swarming_after_hover: 10 # [s]
  duration: 1200 # [s]

  # Proximal control parameters
  proximal: 
    desired_distance: 5.0
    range_multiplier: 1.8 
    steepness_potential: 2.0
    strength_potential: 5.0

  # Motion control parameters
  motion:
    K1: 0.5  # Linear gain
    K2: 0.1  # Angular gain 0.2 for GPS
    K3: 0.1
    move_forward: 0.2 
    interpolate_coeff: 0.95
    fixed_heading: false 
