frame: "gps_origin"

land_at_the_end: false

minimum_height: 2.0 # [m]

flocking:
  # Experiment parameters
  auto_start: false
  swarming_after_hover: 10 # [s]
  duration: 1200 # [s]

  # Proximal control parameters
  proximal: 
    desired_distance: 6.0
    range_multiplier: 3.0        #1.8 for GPS
    steepness_potential: 2.0
    strength_potential: 6.0

  # Motion control parameters
  motion:
    K1: 0.4  # Linear gain 0.5 for GPS
    K2: 0.05  # Angular gain 0.2 for GPS
    K3: 0.1
    move_forward: 0.3 
    interpolate_coeff: 0.95
    fixed_heading: true 




